In [1]:
import pandas as pd

df_clock = pd.read_csv('C:/Users/CHARLIE/Desktop/文字探勘/期末/陳時中_社群網路節點.csv')
df_jiang = pd.read_csv('C:/Users/CHARLIE/Desktop/文字探勘/期末/蔣萬安_社群網路節點.csv')
df_33 = pd.read_csv('C:/Users/CHARLIE/Desktop/文字探勘/期末/黃珊珊_社群網路節點.csv')

In [2]:
df = pd.concat([df_clock, df_jiang, df_33], axis = 0)
df

   Source Target  Weight
0     陳時中    蔣萬安     306
1     陳時中    柯文哲     297
2     陳時中    黃珊珊     259
3     陳時中     疫苗     236
4     陳時中     防疫     186
..    ...    ...     ...
28    黃珊珊     里長      11
29    黃珊珊     中央      11
30    黃珊珊     柯P      11
31    黃珊珊     棄保      11
32    黃珊珊     證實      11

[122 rows x 3 columns]

In [3]:
df_node = pd.DataFrame({'Node':df['Target']})
df_node

   Node
0   蔣萬安
1   柯文哲
2   黃珊珊
3    疫苗
4    防疫
..  ...
28   里長
29   中央
30   柯P
31   棄保
32   證實

[122 rows x 1 columns]

In [4]:
df_node.drop_duplicates(subset='Node', keep='first', inplace=True)

In [5]:
df_node

   Node
0   蔣萬安
1   柯文哲
2   黃珊珊
3    疫苗
4    防疫
..  ...
28   里長
29   中央
30   柯P
31   棄保
32   證實

[80 rows x 1 columns]

In [6]:
id_node = []
for i in range(len(df_node['Node'])):
    id_node.append(i+1)
df_node['Id'] = id_node

In [7]:
df_node

   Node  Id
0   蔣萬安   1
1   柯文哲   2
2   黃珊珊   3
3    疫苗   4
4    防疫   5
..  ...  ..
28   里長  76
29   中央  77
30   柯P  78
31   棄保  79
32   證實  80

[80 rows x 2 columns]

In [8]:
df_node.to_csv('C:/Users/CHARLIE/Desktop/文字探勘/期末/node.csv')

In [14]:
node_id = dict(zip(df_node['Node'], df_node['Id']))

In [ ]:
node_id

In [25]:
target = []
for i in df['Target']:
    target.append(node_id[i])
df['Target_id'] = target

In [28]:
df.to_csv('C:/Users/CHARLIE/Desktop/文字探勘/期末/link.csv')